### ISSUE TITLE
Variable name for sha or source file

### ISSUE THREAD

**Issue by fnasser** [openshift/contra-lib#24]
There is another tool used by some products that already injects the sha of the sources into the spec file -- needed for finding the file created by the Brew "exploded sources feature".

It uses the name (as suggested by RCM/DevOps) "commitid"

%global commitid ec578805a5334229895fba20d939495a74f27cad

This is later referenced in the spec file:

Source0: httpd-%{commitid}.tar.gz

**Comment by arilivigni** [comment]
@fnasser I am not sure this is the right repo for your issue

**Comment by fnasser** [comment]
You are right.  Wrong contra- repo.  Closing
